trigger:
- ado-rrtech

pool:
  name: 'Default'
#  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DskipTests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'artifact-dev'
    publishLocation: 'pipeline'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'artifact-dev'
    targetPath: '$(Pipeline.Workspace)'
